### ISSUE TITLE
初始化

### ISSUE THREAD

**Issue by luckxs2008** [WhereNextToGo/StudyCommunity#1]
你好 方便贴下数据库sql语句么 和完善下初始化操作流程么

**Comment by WhereNextToGo** [comment]
项目还没写完，写完了sql会发上去的，最近有点忙还没更新





***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WhereNextToGo/StudyCommunity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月27日(星期一) 下午3:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[WhereNextToGo/StudyCommunity] 初始化 (Issue #1)





 
你好 方便贴下数据库sql语句么 和完善下初始化操作流程么
